apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-jib-skaffold-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-jib-skaffold-app
  template:
    metadata:
      labels:
        app: spring-jib-skaffold-app
    spec:
      containers:
        - name: spring-jib-skaffold-app-pod
          image: spring-jib-skaffold-app
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-jib-skaffold-app-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30002
  selector:
    app: spring-jib-skaffold-app