---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-jib-app-dep
  labels:
    app: spring-jib-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-jib-app
  template:
    metadata:
      labels:
        app: spring-jib-app
    spec:
      containers:
        - name: spring-jib-app
#          image: arturix/spring-jib-app:latest
          image: 232766839285.dkr.ecr.us-east-2.amazonaws.com/spring-jib-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spring-jib-app-ext-svc
spec:
  selector:
    app: spring-jib-app
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      protocol: TCP